---
name: 'Label checker for pull requests'
description: 'Checks pull requests for given labels'
author: 'John Boyes'
inputs:
  one-of:
    description: >
      A JSON array of labels.
      Each pull request must be labeled with exactly one of these labels.
    required: false
  none-of:
    description: >
      A JSON array of labels.
      Each pull request must not be labeled with any of these labels.
    required: false
  github-token:
    description: >
      See this link for an example of how to pass in the GitHub token:
      https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#example-passing-github_token-as-an-input
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    LABELS_ONE_REQUIRED: ${{ inputs.one-of }}
    LABELS_NONE_REQUIRED: ${{ inputs.none-of }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
