---
name: Check Docker image with current semantic version is also tagged with latest
on:  # yamllint disable-line rule:truthy
  push

jobs:

  check_latest_tag:
    runs-on: ubuntu-22.04
    steps:

      - name: Is latest tagged correctly
        id: is_latest_tagged_correctly
        env:
          image_ver: v1.6.13
        run: |
          docker pull agilepathway/pull-request-label-checker:${{ env.image_ver }}
          echo "IS_LATEST_TAGGED_CORRECTLY=$(docker image inspect agilepathway/pull-request-label-checker:${{ env.image_ver }} | jq -r '.[] | (.RepoTags) | any( . == "agilepathway/pull-request-label-checker:latest") ')" >> "$GITHUB_OUTPUT"
      
      - name: Echo echo
        run: |
          echo ${{ steps.is_latest_tagged_correctly.outputs.IS_LATEST_TAGGED_CORRECTLY }} 
      
      - name: Fail if latest is not tagged correctly
        if: ${{ steps.is_latest_tagged_correctly.outputs.IS_LATEST_TAGGED_CORRECTLY == 'false' }} 
        uses: actions/github-script@v3
        with:
          script: |
                core.setFailed('Latest is not tagged correctly')
