---
name: Check Docker image with current semantic version is also tagged with latest
on:  # yamllint disable-line rule:truthy
  push

jobs:

  check_latest_tag:
    runs-on: ubuntu-22.04
    steps:

      - name: Get image tags
        id: get_image_tags
        env:
          image_ver: v1.6.13
        run: |
          docker pull agilepathway/pull-request-label-checker:${{ env.image_ver }}
          docker image inspect agilepathway/pull-request-label-checker:${{ env.image_ver }} | jq -r '.[] | (.RepoTags) | any(index("${{ env.image_ver }}")) '
