---
name: Check Docker image with current semantic version is also tagged with latest
on:  # yamllint disable-line rule:truthy
  push

jobs:

  check_latest_tag:
    runs-on: ubuntu-22.04
    steps:

      - name: Check Docker image with current semantic version is also tagged with latest
        id: docker_semver
        uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.1
        with:
          org: 'agilepathway'  # Docker Hub user or organisation name
          repo: 'pull-request-label-checker'  # Docker Hub repository name

      - name: Inspect image
        run: |
          docker pull agilepathway/pull-request-label-checker:${{ steps.docker_semver.outputs.tag }}
          docker image inspect agilepathway/pull-request-label-checker:${{ steps.docker_semver.outputs.tag }} | jq -r '.[] | (.RepoTags)'
