---
name: Label Checker
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_semver_label:
    name: Check for semantic version label
    runs-on: ubuntu-22.04
    steps:
      - uses: agilepathway/label-checker@be847a108e0a42beaa699bb9c9783c7bc01ef2ee  # v2.0.0
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}
