---
name: Check Docker latest tag is correct
on:  # yamllint disable-line rule:truthy
  push

jobs:

  check_latest_tag:
    runs-on: ubuntu-22.04
    steps:

      - name: Inspect image
        run: |
          docker pull agilepathway/pull-request-label-checker:latest
          docker image inspect agilepathway/pull-request-label-checker:latest
