---
name: Check Docker image with current semantic version is also tagged with latest
on:  # yamllint disable-line rule:truthy
  push

jobs:

  check_latest_tag:
    runs-on: ubuntu-22.04
    steps:

      - name: Is latest tagged correctly
        id: is_latest_tagged_correctly
        env:
          repo: agilepathway/pull-request-label-checker
          image_ver: v1.6.13
        # yamllint disable rule:line-length
        run: |
          docker pull ${{env.repo}}:${{ env.image_ver }}
          echo "IS_LATEST_TAGGED_CORRECTLY=$(docker image inspect ${{env.repo}}:${{ env.image_ver }} | jq -r '.[] | (.RepoTags) | any( . == "${{env.repo}}:latest") ')" >> "$GITHUB_OUTPUT"
        # yamllint enable rule:line-length

      - name: Fail if latest is not tagged correctly
        if: ${{ steps.is_latest_tagged_correctly.outputs.IS_LATEST_TAGGED_CORRECTLY == 'false' }}
        uses: actions/github-script@v3
        with:
          script: |
                core.setFailed('Latest is not tagged correctly')
