---
# See ../DEPENDENCIES.md#workaround-for-other-dependencies
name: Dependabot hack
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - never-trigger-this-dependabot-hack-workflow

jobs:

  dependabot_hack:
    name: Ensure dependabot version checks
    runs-on: ubuntu-22.04
    steps:

      # update the version in these places manually when Dependabot changes it here:
      # 1. the base image in the Dockerfile
      # 2. github_tag_and_release.yml
      # 3. integration_test.yml
      # 4. virtual_test.yml
      # 5. the go.mod (if it is a major or minor version change e.g. 1.14 to 1.15)
      - uses: golang/go@go1.27.1
