---
name: Release

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - closed
    branches:
      - master

jobs:

  tag:
    if: github.event.pull_request.merged
    permissions:
      contents: write
    name: Tag semantic version
    runs-on: ubuntu-22.04
    outputs:
      semver: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@v1.3.2
        id: tag
        with:
          release_branch: master
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: tag
    permissions:
      contents: write
    name: Create GitHub Release
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
