---
on:  # yamllint disable-line rule:truthy
  # Run the tests on every push, and also at 3am every night
  push:
  schedule:
    - cron: '0 3 * * *'  # * is a special character in YAML so you have to quote this string
name: Tests
jobs:
  tests:
    name: Integration
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.6
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Tests
        env:
          INPUT_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go test -integration -v .
