---
name: Lint checks

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: 24.21.0
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check formatting and lint
        run: npm run check
      - name: Type check
        run: npm run typecheck
