name: Tag

on:
  pull_request:
    types: 
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag 
        uses: K-Phoen/semver-release-action@v1.3.1
        with:
          release_branch: master
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
