---
on:  # yamllint disable-line rule:truthy
  # Run the tests on every push and pull request, and also at 3am every night
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
  schedule:
    - cron: '0 3 * * *'  # * is a special character in YAML so you have to quote this string
name: Tests
jobs:
  tests:
    name: Virtual
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.21.0
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Tests
        run: |
          node --test test/check_labels.test.ts
          TEST_GITHUB_PLATFORM=enterprise-cloud node --test test/check_labels.test.ts
          TEST_GITHUB_PLATFORM=enterprise-server node --test test/check_labels.test.ts
